import React from 'react'
import RestCards from './RestaurantCards';

//Dummy data from swiggy API ( for practice )
const resObj = [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "224022",
        name: "Oven Story Pizza",
        uuid: "2fcd35d0-e1a7-4555-9477-91bc3e2d0a37",
        city: "7",
        area: "Newtown",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "ab979bffbd658e74de650a15ca0092a3",
        cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "â¹400 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "ovenstory-pizza-new-town-salt-lake",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "UNIT NO 220, 2ND FLOOR, ACTION AREA 1B, NEW TOWN, KOLKATA 700156",
        locality: "ACTION AREA 1B",
        parentId: 3534,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4400,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4400,
          message: "",
          title: "Delivery Charge",
          amount: "4400",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7278007~p=1~eid=00000189-0d8c-2028-2291-9b6900cf0164~srvts=1688149434408",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "â¹125 OFF",
          subHeader: "ABOVE â¹699",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "224022",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "135901",
        name: "Noodles Shoodlez",
        uuid: "190e44a9-5a4f-466e-85df-a99f23f5b9ae",
        city: "7",
        area: "Newtown",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "bxpeobnfjekqmhyz0jp0",
        cuisines: ["Chinese", "Fast Food", "North Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "â¹300 FOR TWO",
        deliveryTime: 18,
        minDeliveryTime: 18,
        maxDeliveryTime: 18,
        slaString: "18 MINS",
        lastMileTravel: 1.2000000476837158,
        slugs: {
          restaurant: "noodles-shoodlez-new-town-rajarhat",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "JL NO 33, MOUZA CHAKPACHURIA, VILLAGE - ACTION AREA 1 D, NEWTOWN - 700156, RAJARHAT, NORTH TWENTY FOUR PARGANAS, WEST BENGAL 700156",
        locality: "Opposite Unitech Gate 1",
        parentId: 149968,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3600,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3600,
          message: "",
          title: "Delivery Charge",
          amount: "3600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "â¹125 OFF",
          subHeader: "ABOVE â¹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "135901",
          deliveryTime: 18,
          minDeliveryTime: 18,
          maxDeliveryTime: 18,
          lastMileTravel: 1.2000000476837158,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "147193",
        name: "CFC (Calcutta Fried Chicken)",
        uuid: "915320aa-671f-452b-8e3e-7b1b1be1d075",
        city: "7",
        area: "Newtown",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "dnb1g0jn9hjqtfkyvzak",
        cuisines: ["Snacks"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "â¹250 FOR TWO",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        slaString: "25 MINS",
        lastMileTravel: 0.800000011920929,
        slugs: {
          restaurant: "cfc-calcutta-fried-chicken-rajarhat-rajarhat-2",
          city: "kolkata",
        },
        cityState: "7",
        address: "Shop No.A-46, NKDA Market , Unitech Gate No.1 , Newtown",
        locality: "Rajarhat",
        parentId: 56405,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3600,
          message: "",
          title: "Delivery Charge",
          amount: "3600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.8 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "40% OFF",
          subHeader: "UPTO â¹80",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "147193",
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          lastMileTravel: 0.800000011920929,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "242966",
        name: "La Pino'z Pizza",
        uuid: "590e7dd7-4dd1-4961-92f1-63a18a88e9ee",
        city: "7",
        area: "Bidhannagar",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "vipohbpqczfrv6jnycwa",
        cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "â¹250 FOR TWO",
        deliveryTime: 51,
        minDeliveryTime: 51,
        maxDeliveryTime: 51,
        slaString: "51 MINS",
        lastMileTravel: 6.900000095367432,
        slugs: {
          restaurant: "la-pino'z-sector-v-salt-lake-sector-v-salt-lake",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "SHOP NO 3 GROUND FLOOR  NETGURU BUILDING  E2 4 BLOCK GP SECTOR V  SALT LAKE  BIDHANNAGAR  KOLKATA   700091",
        locality: "Sector V Salt Lake",
        parentId: 4961,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 7900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7900,
          message: "",
          title: "Delivery Charge",
          amount: "7900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7101844~p=7~eid=00000189-0d8c-2028-2291-9b6b00cf0718~srvts=1688149434408",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.9 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "15% OFF",
          subHeader: "UPTO â¹80",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "242966",
          deliveryTime: 51,
          minDeliveryTime: 51,
          maxDeliveryTime: 51,
          lastMileTravel: 6.900000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.0",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "394012",
        name: "Bawarchi",
        uuid: "73ffbc11-3de4-48e7-8c7a-105c83902953",
        city: "7",
        area: "Rajarhat",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "d3wikv5f99qdal52wylb",
        cuisines: ["Biryani", "Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "â¹300 FOR TWO",
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        slaString: "19 MINS",
        lastMileTravel: 2,
        slugs: {
          restaurant: "bawarchi-restro-rajarhat-rajarhat",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "Ramjan Ali Khan, Chakpachuria, P &amp; Vill - Patharghata, Rajarhat, North Twenty Four Parganas, West Bengal",
        locality: "Chakpachuria",
        parentId: 100,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3600,
          message: "",
          title: "Delivery Charge",
          amount: "3600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "Closes soon",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "394012",
          deliveryTime: 19,
          minDeliveryTime: 19,
          maxDeliveryTime: 19,
          lastMileTravel: 2,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.8",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "31199",
        name: "Burger Home",
        uuid: "a97ce6ff-42d5-435b-acd1-7a564cbe50ea",
        city: "7",
        area: "Newtown",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "lcfofbsnrik7aa6gp6fm",
        cuisines: ["Fast Food"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "â¹250 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 0.8999999761581421,
        slugs: {
          restaurant: "burger-home-rajarhat-rajarhat",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "Shop A -13, NKDA Market, Opposite Unitech Gate no.1, Kolkata- 700156",
        locality: "Opposite Unitech Gate No.1",
        parentId: 1861,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3600,
          message: "",
          title: "Delivery Charge",
          amount: "3600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.8 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO â¹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "31199",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 0.8999999761581421,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.7",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "80732",
        name: "Incredible-e-naturals",
        uuid: "fa955b12-689c-46ca-8644-272f0b1602fc",
        city: "7",
        area: "Newtown",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "ofk1u5lcihoa7hqqc0ar",
        cuisines: ["Continental", "Fast Food", "Snacks", "Beverages"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "â¹250 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 0.800000011920929,
        slugs: {
          restaurant: "incredible-e-naturals-rajarhat-rajarhat",
          city: "kolkata",
        },
        cityState: "7",
        address: "C-6, Opp Unitech Gate No-1, Kolkata 156",
        locality: "Unitech Gate No.1",
        parentId: 106259,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3600,
          message: "",
          title: "Delivery Charge",
          amount: "3600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.8 kms",
        hasSurge: false,
        sla: {
          restaurantId: "80732",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 0.800000011920929,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.7",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "494919",
        name: "Pizza World",
        uuid: "1c825979-2ec9-4cb4-b507-993f082c47d9",
        city: "7",
        area: "Rajarhat",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "xyn4k5okh0y7smlyisjh",
        cuisines: ["Pizzas", "Italian-American", "Snacks", "Beverages"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "â¹200 FOR TWO",
        deliveryTime: 40,
        minDeliveryTime: 40,
        maxDeliveryTime: 40,
        slaString: "40 MINS",
        lastMileTravel: 1,
        slugs: {
          restaurant: "pizza-world-rajarhat-rajarhat",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "J.L.NO-33,MOUJA -CHAKPANCHURIA VILLAGE,P.S-NEWTOWN,NORTH 24 PARGANA,KOLKATA-700156,MAHISBATHAN-II,RAJARHAT,NORTH TWENTY FOUR PARGANAS,WEST BENGAL-700156",
        locality: "",
        parentId: 9468,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3600,
          message: "",
          title: "Delivery Charge",
          amount: "3600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "Closes soon",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "494919",
          deliveryTime: 40,
          minDeliveryTime: 40,
          maxDeliveryTime: 40,
          lastMileTravel: 1,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "435966",
        name: "Keventers Ice Cream",
        uuid: "3dcc665c-ab67-4d55-a82e-98b929a93d64",
        city: "7",
        area: "Chinar Park",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "5220cf2d5049dd54b0fb98bbb3d5a652",
        cuisines: ["Ice Cream", "Desserts"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "â¹200 FOR TWO",
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        slaString: "35 MINS",
        lastMileTravel: 8.800000190734863,
        slugs: {
          restaurant: "keventers-ice-creamery-rajarhat-chinar-park",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "Plot No. 10/319, Near Bhola Football Ground, Hatiara Rajarhat, Kolkata- 700159 West Bengal - 700159",
        locality: "Rajarhat",
        parentId: 272044,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 9900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 9900,
          message: "",
          title: "Delivery Charge",
          amount: "9900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7168623~p=10~eid=00000189-0d8c-2028-2291-9b6c00cf0a0c~srvts=1688149434408",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "8.8 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO â¹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "435966",
          deliveryTime: 35,
          minDeliveryTime: 35,
          maxDeliveryTime: 35,
          lastMileTravel: 8.800000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "484123",
        name: "The Pizzerian",
        uuid: "935e725d-828a-4fe1-a088-b37c6cd9e108",
        city: "7",
        area: "New Town",
        totalRatingsString: "50+ ratings",
        cloudinaryImageId: "ew0gcyo3z9pll9wpd7fm",
        cuisines: ["Pizzas", "Pastas", "Fast Food", "Beverages"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "â¹300 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 1.2000000476837158,
        slugs: {
          restaurant: "the-pizzerian-rajarhat-rajarhat",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "Newtown opposite tapas Xerox shop Beside cafeteria club house, ward no -27 Bidhannagar rajarhat municipal corporation north 24 pargans Pincode - 700156",
        locality: "Rajarhat",
        parentId: 290723,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3600,
          message: "",
          title: "Delivery Charge",
          amount: "3600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "484123",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 1.2000000476837158,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.4",
        totalRatings: 50,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "506319",
        name: "The Pizza Box",
        uuid: "38491374-23ea-4a2e-be80-82d1dacba11c",
        city: "7",
        area: "Rajarhat",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "dfeh6bqghtviwc4wb9tn",
        cuisines: ["Pizzas", "Italian", "Fast Food"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "â¹400 FOR TWO",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        slaString: "27 MINS",
        lastMileTravel: 1,
        slugs: {
          restaurant: "the-pizza-box-rajarhat-rajarhat",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "J.L. No.- 33, Mouja- Chakpanchuria village, P.S- Newtown, North 24 pargana, Kolkata-700156, MAHISBATHAN-II, RAJARHAT, North Twenty Four Parganas, West Bengal - 700156",
        locality: "Mouja- Chakpanchuria",
        parentId: 212550,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3600,
          message: "",
          title: "Delivery Charge",
          amount: "3600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "Closes soon",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "506319",
          deliveryTime: 27,
          minDeliveryTime: 27,
          maxDeliveryTime: 27,
          lastMileTravel: 1,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "2.7",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "635465",
        name: "Country Chef",
        uuid: "38888641-5a01-4a6a-b6ab-0b8d9eb31cb4",
        city: "7",
        area: "Eco Park Newtown",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "vei3s75h2y8j8dt254ka",
        cuisines: ["Chinese", "Beverages", "Snacks"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "â¹400 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 0.8999999761581421,
        slugs: {
          restaurant: "country-chef-rajarhat-rajarhat",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "NEWTOWN,VILL+P.O- CHAKPANCHURIA,P.S-TECHNO CITY,SHOP NO-A/43,, RAJARHAT BISHNUPUR-I, RAJARHAT, North Twenty Four Parganas,",
        locality: "New town",
        parentId: 383847,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3600,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3600,
          message: "",
          title: "Delivery Charge",
          amount: "3600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "Closes soon",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.8 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "30% OFF",
          subHeader: "UPTO â¹150",
          discountTag: "SAVE BIG",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "635465",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 0.8999999761581421,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "417023",
        name: "Pizza Hut",
        uuid: "a19313b1-f04a-4bfc-9cf7-281538d22b87",
        city: "7",
        area: "Rajarhat",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        cuisines: ["Pizzas"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "â¹350 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "pizza-hut-rosedale-new-town-rajarhat",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "Pizza Hut, Rosedale Plaza Complex, Ground Floor, Plot No. AA-III BLK-3, New Town, , RAJARHAT, North Twenty Four Parganas, West Bengal, 700160",
        locality: "Rosedale New town",
        parentId: 721,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4400,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4400,
          message: "",
          title: "Delivery Charge",
          amount: "4400",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO â¹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "417023",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.8",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "563432",
        name: "MBA Pizza Wala",
        uuid: "480570d2-fb14-43ce-8487-d63ce2506e4e",
        city: "7",
        area: "Rajarhat",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "ol8bmmlo2akqktq6dv6t",
        cuisines: ["Italian", "Fast Food", "Chinese", "Beverages"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "â¹400 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 1.2000000476837158,
        slugs: {
          restaurant: "m.b.a-pizzawala-rajarhat-rajarhat",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "NEWTOWN,OPPOSITE TAPAS XEROX SHOP BESIDE CAFETERIA CLUB HOUSE, WARD NO-27, BIDHANNAGAR-RAJARHAT MUNICIPAL CORPORATION, North Twenty Four Parganas, West Bengal - 700156",
        locality: "North Twenty Four Parganas",
        parentId: 321125,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3600,
          message: "",
          title: "Delivery Charge",
          amount: "3600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "563432",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 1.2000000476837158,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "2.8",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "475019",
        name: "The Pizza Castle",
        uuid: "e58edd5e-dda9-4395-8b7f-9c700fc5bdc5",
        city: "7",
        area: "Rajarhat",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "zrjfimet9cfg68m2ujsv",
        cuisines: ["Pizzas", "Combo"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "â¹400 FOR TWO",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        slaString: "27 MINS",
        lastMileTravel: 1,
        slugs: {
          restaurant: "the-pizza-castle-rajarhat-rajarhat",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "J.L. No.- 33, Mouja- Chakpanchuria village, P.S- Newtown, North 24 pargana, Kolkata-700156, MAHISBATHAN-II, RAJARHAT, North Twenty Four Parganas, West Bengal - 700156",
        locality: "Chakpanchuria Village",
        parentId: 212559,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3600,
          message: "",
          title: "Delivery Charge",
          amount: "3600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "Closes soon",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "475019",
          deliveryTime: 27,
          minDeliveryTime: 27,
          maxDeliveryTime: 27,
          lastMileTravel: 1,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "224023",
        name: "Oven Story Pizza",
        uuid: "2fcd35d0-e1a7-4555-9477-91bc3e2d0a37",
        city: "7",
        area: "Newtown",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "ab979bffbd658e74de650a15ca0092a3",
        cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "â¹400 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "ovenstory-pizza-new-town-salt-lake",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "UNIT NO 220, 2ND FLOOR, ACTION AREA 1B, NEW TOWN, KOLKATA 700156",
        locality: "ACTION AREA 1B",
        parentId: 3534,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4400,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4400,
          message: "",
          title: "Delivery Charge",
          amount: "4400",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7278007~p=1~eid=00000189-0d8c-2028-2291-9b6900cf0164~srvts=1688149434408",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "â¹125 OFF",
          subHeader: "ABOVE â¹699",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "224023",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
  ]

const Body = () => {
    return (
        <div className="body-comp">
          <div className="rest-cont">
            <h2 className="rest-heading">Top restaurant chains in Mathura</h2>
            <div className="cards-cont">
              {
                resObj.map((res) => (
                <RestCards key={res.data.id} resData = {res} /> //key is here for uniquely distinguish the cards 
                ))
              }
            </div>
          </div>
        </div>
      );
}

export default Body

